server:
  port: 8080 # ??????

spring:
  ai:
    deepseek:
      api-key: sk-7093e866acf74aa3b189ef313838cb8d # ?? DeepSeek Api Key, ??????
      base-url: https://api.deepseek.com # DeepSeek ??? URL, ???????? api.deepseek.com
      chat:
        options:
          model: deepseek-chat # 使用哪个模型
          temperature: 0.8 # 温度值
