server:
  port: 8080 # ??????

spring:
  ai:
    deepseek:
      api-key: sk-2f3ed14925104d549da53788caff8cb7 # ?? DeepSeek Api Key, ??????
      base-url: https://api.deepseek.com # DeepSeek ??? URL, ???????? api.deepseek.com
      chat:
        options:
          model: deepseek-chat # ??????
          temperature: 0.8 # ???
